In [51]:
# This program will take Product Sales data from local drive# will clean it up for blank spaces, NaNs and non-logical data# will update the input file with Summary Sales and Average Prices by productimport pandas as pd
import numpy as np

df = pd.read_excel('Products_data.xlsx',header = 0)

df.dropna(how='all', inplace=True)

df.dropna(axis=1, how='all', inplace=True)

df.columns = df.iloc[0]
df = df.drop(0).reset_index(drop=True)

df.replace('', np.nan, inplace=True) 
df.dropna(inplace=True) 
df = df[~(df == 0).any(axis=1)]

# Wherever Price is non-numeric - > change it to NaN
df['Price (USD)'] = pd.to_numeric(df['Price (USD)'], errors='coerce') 
df.dropna(subset=['Price (USD)'], inplace=True)

# Sort by brand and reset the index
df = df.sort_values(by='Brand')
df.reset_index(drop=True, inplace=True)

print(df)


#Give the Sales by Brand
Brand_counts = df.groupby('Brand').size().reset_index(name='Total Sales')
print('Sales by Brand:',Brand_counts)

#Give average price for the Brands
Brand_avg_price = df.groupby('Brand')['Price (USD)'].mean().reset_index(name='Average_price') 
print('Average Price by Brand:',Brand_avg_price)

with pd.ExcelWriter('Products_data.xlsx', mode='a', engine='openpyxl') as writer: 
    Brand_counts.to_excel(writer, sheet_name='Brand_Total_Rows', index=False) 
    Brand_avg_price.to_excel(writer, sheet_name='Brand_Avg_Price', index=False)

0       Brand       Device          Model Country of Origin  \
0        Acer       Aspire              5            Taiwan
1        Acer        Swift              3            Taiwan
2        Acer     Predator     Helios 300            Taiwan
3       Apple         iPad  Pro 12.9-inch     United States
4       Apple      MacBook    Pro 14-inch     United States
5       Apple       iPhone     13 Pro Max     United States
6        Asus          ROG   Zephyrus G14            Taiwan
7        Asus          TUF     Gaming A15            Taiwan
8        Asus      ZenBook             14            Taiwan
9        Dell   UltraSharp         U2720Q             China
10       Dell    Alienware         m15 R5     United States
11       Dell          XPS             13     United States
12     Google         Nest        Hub Max     United States
13     Google    Pixelbook             Go     United States
14     Google        Pixel          6 Pro     United States
15         HP      Spectre           x360     United States
16         HP        Elite      Dragonfly     United States
17         HP     Pavilion           x360     United States
18     Lenovo       Legion             7i             China
19     Lenovo      IdeaPad          5 Pro             China
20     Lenovo     ThinkPad      X1 Carbon             China
21  Microsoft      Surface          Pro 8     United States
22  Microsoft      Surface       Laptop 4     United States
23  Microsoft         Xbox       Series X     United States
24    Samsung       Galaxy      S21 Ultra       South Korea
25    Samsung       Galaxy        Tab S7+       South Korea
26    Samsung      Odyssey             G9       South Korea
27       Sony           WH        1000XM4          Malaysia
28       Sony  PlayStation              5             Japan
29       Sony       Xperia          1 III             Japan

0       Date of Release  Price (USD)
0   2021-01-30 00:00:00        599.0
1   2021-02-10 00:00:00        699.0
2   2021-02-17 00:00:00       1299.0
3   2021-05-21 00:00:00       1099.0
4   2021-10-26 00:00:00       1999.0
5   2021-09-24 00:00:00       1099.0
6   2021-03-15 00:00:00       1499.0
7   2021-03-20 00:00:00       1199.0
8   2021-01-15 00:00:00        799.0
9   2020-12-25 00:00:00        499.0
10  2021-04-20 00:00:00       1999.0
11  2021-01-28 00:00:00        999.0
12  2021-03-30 00:00:00        229.0
13  2021-06-17 00:00:00        649.0
14  2021-10-19 00:00:00        899.0
15  2021-04-16 00:00:00       1349.0
16  2021-06-28 00:00:00       1799.0
17  2021-05-14 00:00:00        749.0
18  2021-04-05 00:00:00       1499.0
19  2021-03-10 00:00:00        999.0
20  2021-02-15 00:00:00       1429.0
21  2021-10-05 00:00:00        899.0
22  2021-04-15 00:00:00        999.0
23  2020-11-10 00:00:00        499.0
24  2021-01-29 00:00:00       1199.0
25  2020-08-21 00:00:00        849.0
26  2020-07-22 00:00:00       1699.0
27  2020-08-06 00:00:00        349.0
28  2020-11-12 00:00:00        499.0
29  2021-08-19 00:00:00       1299.0
Sales by Brand:        Brand  Total Sales
0       Acer            3
1      Apple            3
2       Asus            3
3       Dell            3
4     Google            3
5         HP            3
6     Lenovo            3
7  Microsoft            3
8    Samsung            3
9       Sony            3
Average Price by Brand:        Brand  Average_price
0       Acer     865.666667
1      Apple    1399.000000
2       Asus    1165.666667
3       Dell    1165.666667
4     Google     592.333333
5         HP    1299.000000
6     Lenovo    1309.000000
7  Microsoft     799.000000
8    Samsung    1249.000000
9       Sony     715.666667